POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "username": "adamSecond",
  "password": "bin1234"
}

###

POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "username": "adamSecond",
  "password": "bin1234"
}

###

POST http://localhost:8080/api/auth/boards/post
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtMjMiLCJleHAiOjE2NjYxNjU5NjgsImlhdCI6MTY2NjA3OTU2OH0.b8juBXdEX-9q4ynDLvCAk-txybfEscvvGkY_PoX6Rk8

{
  "content": "Parker ",
  "title": "adam"
}


###
GET http://localhost:8080/api/auth/boards/myBoard
Content-Type: application/json
Access_Token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtMjMiLCJleHAiOjE2NjYxNjU5NjgsImlhdCI6MTY2NjA3OTU2OH0.b8juBXdEX-9q4ynDLvCAk-txybfEscvvGkY_PoX6Rk8




###

POST http://localhost:8080/api/auth/board/comment/1
Content-Type: application/json
Access_token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtMjMiLCJleHAiOjE2NjYxNjUwNTAsImlhdCI6MTY2NjA3ODY1MH0.F8qZ6j727YSNFNpRdgG0OXLb6EJopOvi-KN9pudOO8Q

{
  "content": "@!@@@"
}
###

GET http://localhost:8080/api/auth/board/comment
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtMjMiLCJleHAiOjE2Njc0MDAzNTksImlhdCI6MTY2NjA4NjM1OX0.ycT_Im00sE25w1cFq8lIjFBDlDlL5ldmcHMPXG55-Ys



###


GET http://localhost:8080/api/issue/token
Accept: application/json
Refresh_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3b25iaW4zQGdtYWlsLmNvbSIsImV4cCI6MTY2NjEwMTQzNSwiaWF0IjoxNjY2MDE1MDM1fQ.qoilL1J0v22nDYG7kN-aD665EHUWlIt-nL3PwbUPT-A

###
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "username": "wonbin@mail.com",
  "password": "bin1234"
}

###





GET http://localhost:8080/api/auth/boards
Content-Type: application/json
Access_Token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtMjMiLCJleHAiOjE2NjYxNjQ3NDQsImlhdCI6MTY2NjA3ODM0NH0.o2UZmJTc3LHsClMJdgtFFHlg9V8l8YGMFcNs8EH7vdI

###

DELETE http://localhost:8080/api/auth/boards/delete/1
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtMjMiLCJleHAiOjE2NjYxNjU5NjgsImlhdCI6MTY2NjA3OTU2OH0.b8juBXdEX-9q4ynDLvCAk-txybfEscvvGkY_PoX6Rk8
###

PUT http://localhost:8080/api/auth/boards/update/1
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtMjMiLCJleHAiOjE2NjYxNjUwNTAsImlhdCI6MTY2NjA3ODY1MH0.F8qZ6j727YSNFNpRdgG0OXLb6EJopOvi-KN9pudOO8Q

{
  "title": "update Title"
}

###
POST http://localhost:8080/api/auth/heart/like/1
Content-Type: application/json
Access_Token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtU2Vjb25kIiwiZXhwIjoxNjY2MTczMzA1LCJpYXQiOjE2NjYwODY5MDV9.zwiTM5CUiMpvElxV5sUbhGONqZA-KVehONUtOmJtpmk

